apiVersion: v1
kind: Secret
metadata:
  name: tickit
type: Opaque
data:
  DB_USERNAME: Y2hhbmdlbWU=
  DB_PASSWORD: Y2hhbmdlbWVhbHNv
  DB_HOST: Y2hhbmdlLm1lLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbQ==
  DB_PORT: NTQzMg==
  DB_DATABASE: dGlja2l0